//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiunecoSimone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public System.Guid Id { get; set; } = Guid.NewGuid();
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public decimal WorkedHour { get; set; }
        public int State { get; set; }
        public string Comment { get; set; }
        public System.DateTime CommentDate { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
